Release/1.0.0
ZenTaKr0fTeR111/MyLittlePokemons pull request #5
Opened 2024-06-29 15:51 UTC by ZenTaKr0fTeR111

<h1>App which displays a list of pokemons</h1>
<h3>Main Screen</h3>
<h6>Shows a list of 20 clickable pokemons using 2 different layouts: standard and special(with superpower).
Special pokemons have a distinctive tint and an icon to indicate what their superpower is.</h6>

![main_activity](https://github.com/ZenTaKr0fTeR111/MyLittlePokemons/assets/89477635/df786f03-0a18-4e27-be6f-303f80184116)
![main_activity_night](https://github.com/ZenTaKr0fTeR111/MyLittlePokemons/assets/89477635/70fd0014-ced3-4d94-aa4a-c297af363383)

<h3>Details Screen</h3>
<h6>Clicking a pokemon item takes us to another activity, which provides detailed information regarding clicked pokemon.</h6>

![details_activity](https://github.com/ZenTaKr0fTeR111/MyLittlePokemons/assets/89477635/926919a8-a1e2-4954-b896-3d1e657a3bf9)
![details_activity_night](https://github.com/ZenTaKr0fTeR111/MyLittlePokemons/assets/89477635/c95ad816-4aa3-47ac-975f-007bd9291831)

2024-06-29 18:48 UTC, pzinkevich42innowise requested changes

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/DetailsActivity.kt
> +                speedValue.text = it.stats[Pokemon.SPEED_KEY].toString()
В идеале хотелось бы видеть отдельные методы настройки каждой логической части экрана, типа
```
fun setupStats(pokemon: Pokemon) { ... }
fun setupSpecs(pokemon(pokemon: Pokemon) {...}
fun setupSpecial(pokemon: Pokemon) { if (pokemon.isSpecial) ... }
```

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/DetailsActivity.kt
> +                    specialImage?.visibility = View.VISIBLE
```suggestion
                    specialImage.isVisible = true
```
`else specialImage.isVisible = false`

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/MainActivity.kt
> +        }
```suggestion
        val pokemonAdapter = PokemonAdapter { id ->
            val intent = Intent(this, DetailsActivity::class.java)
            intent.putIntExtra(Pokemon.POKEMON_ID_KEY, id)
            startActivity(intent)
        }
```
Или же, если хочешь бандл, то есть `bundleOf(Pokemon.POKEMON_ID_KEY to id)`

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/MainActivity.kt
> +        binding.pokemonList.let {
Зачем let ?

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/MainActivity.kt
> +            it.layoutManager = LinearLayoutManager(this)
Это в xml

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/MainActivity.kt
> +                        )!!
Можно без `!!`?

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/PokemonAdapter.kt
> +    private var pokemonList = mapOf<Int, Pokemon>()
```suggestion
    private var pokemonList = emptyList<Pokemon>()
```

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/PokemonAdapter.kt
> +        holder.bind(position + 1)
```suggestion
        holder.bind(pokemonList[position])
```

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/PokemonAdapter.kt
> +        private val oldList: Map<Int, Pokemon>, private val newList: Map<Int, Pokemon>
List

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/PokemonAdapter.kt
> +        pokemonList[position + 1]!!.isSpecial() -> ViewType.SPECIAL_VIEW.ordinal
Без +1

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/PokemonAdapter.kt
> +    //////////////////////// HOLDERS ///////////////////////
В отдельный файл без inner

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +    fun isSpecial() = types.any { it in listOf("Fire", "Water", "Grass") }
Кажется, `Fire, Water, Grass, etc...` это константы или Enum, а `listOf("Fire", "Water", "Grass")` - это в companion `val specialTypes = setOf("Fire", "Water", "Grass")`

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +    }
Реально enum class

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +        1, "Bulbasaur", 7, 69, R.drawable._1,
Ну можно и с 0 начать, тогда и +1 везде делать не придётся

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/res/drawable/fire_icon.png
Все png сконвертировать в webp при помощи встроенной утилиты

2024-06-29 18:48 UTC, pzinkevich42innowise commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.recyclerview.widget.RecyclerView
Может Recycler - это root?

2024-06-30 12:27 UTC, pzinkevich42innowise requested changes

2024-06-30 12:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/MainActivity.kt
> +            intent.putExtra(Pokemon.POKEMON_ID_KEY, position)
```suggestion
        val pokemonAdapter = PokemonAdapter { id ->
            val intent = Intent(this, DetailsActivity::class.java)
            intent.putExtra(Pokemon.POKEMON_ID_KEY, id)
```

2024-06-30 12:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/MainActivity.kt
> +                    )
```suggestion
                    setDrawable(it)
```

2024-06-30 12:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +    GRASS("Grass");
```suggestion
enum class SpecialTypes(val element: String, @DrawableRes val specialImage) {
    FIRE("Fire", R.drawable.fire_icon),
    WATER("Water", R.drawable.water_icon),
    GRASS("Grass", R.drawable.grass_icon);
```

2024-06-30 12:27 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +    fun isSpecial() = types.any { it in SpecialTypes.getElements() }
Разве нет метода containsAny?

2024-06-30 14:11 UTC, ZenTaKr0fTeR111 commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +    fun isSpecial() = types.any { it in SpecialTypes.getElements() }
Нету. Сделал немного по другому но я думаю ты не это имел ввиду

![studio64_HafkPW8xj4](https://github.com/ZenTaKr0fTeR111/MyLittlePokemons/assets/89477635/7117e289-31cb-4be4-be36-20181782e2e3)

2024-06-30 21:22 UTC, pzinkevich42innowise approved these changes
В принципе ок, пересечение можно искать и так

2024-06-30 21:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +    fun isSpecial() = types.any(SpecialTypes.getElements()::contains)
нашёл что искал:
```suggestion
    fun isSpecial() = types.intersect(SpecialTypes.getElements).isNotEmpty()
```
Я думаю это поинтереснее выглядит

2024-06-30 21:22 UTC, pzinkevich42innowise commented on app/src/main/java/com/example/mylittlepokemons/data/Pokemon.kt
> +    fun isSpecial() = types.any { it in SpecialTypes.getElements() }
Вообще это имел в виде, но можно также проверить не пустое ли пересечение двух множеств

2024-06-30 22:10 UTC, merged